# RandomGift configuration

# Items that are chosen at random
#  - 'ID[:data value] Quantity'
items:
  - '267 1'
  - '256 1'
  - '257 1'
  - '258 1'
  - '306 1'
  - '307 1'
  - '308 1'
  - '309 1'
  - '264 1'
  
# Minimum amount of players required to be online
minimum-players: 3

# Cooldown time - minutes before RandomGift can be used again
cooldown-time: 5

# Broadcast Message - Broadcasts a message to all users
broadcast-message: true 

# Version checker - checks for an update on startup and displays a message if there is a more recent version available
version-check: true

# Statistic data
# Plugin Metrics is used to collect anonymous statistic data about the plugins usage and sends it to http://mcstats.org/plugin/randomgift
# This plugin also sends its current version number back to the developer for statistical purposes. 
# This information is simply used for tracking current versions in use, and the data collected will only be seen by the developer(s).
collect-statistics: true