# RandomGift configuration
# Detailed information at http://dev.bukkit.org/bukkit-plugins/randomgift/

# Items that are chosen at random
#  - 'ID[:data value] Quantity'
items:
  - '267 1'
  - '256 1'
  - '257 1'
  - '258 1'
  - '306 1'
  - '307 1'
  - '308 1'
  - '309 1'
  - '264 1'
  
# Minimum amount of players required to be online to trigger a gift
minimum-players: 3

# Include players without the 'receive' permission in the minimum player count
all-players: true

# Amount of minutes before RandomGift can be used again
cooldown-time: 5

# Surprise a player with the gift of death (but they still receive a nice gift too)
death-mode: true

# Broadcasts a message to the entire server when a player receives a gift
broadcast-message: true 

# Checks for an update on startup and displays a message if there is a more recent version available
version-check: true

# Enable debug mode. This will output a lot of information to console.
debug-mode: false

# Statistic data
# Plugin Metrics is used to collect anonymous statistic data about the plugins usage and sends it to http://mcstats.org/plugin/randomgift
# This plugin also sends its current version number back to the developer for statistical purposes. 
# This information is simply used for tracking current versions in use, and the data collected will only be seen by the developer(s).
collect-statistics: true